export const DOCTOR_FORM_FIELDS = [
  {
    name: "fullName",
    label: "ПІБ",
    component: "input",
    type: "text",
    placeholder: "Введіть повне імʼя лікаря",
    required: true,
  },
  {
    name: "specialty",
    label: "Спеціалізація",
    component: "input",
    type: "text",
    placeholder: "Наприклад: терапевт, хірург",
    required: true,
  },
  {
    name: "email",
    label: "Email",
    component: "input",
    type: "email",
    placeholder: "example@email.com",
    required: true,
  },
  {
    name: "phone",
    label: "Телефон",
    component: "input",
    type: "tel",
    placeholder: "+380 XX XXX XX XX",
    required: true,
  },
  {
    name: "room",
    label: "Кабінет",
    component: "input",
    type: "text",
    placeholder: "Номер кабінету",
    required: true,
  },
  {
    name: "notes",
    label: "Додаткові нотатки",
    component: "textarea",
    placeholder: "Додаткова інформація про лікаря (необовʼязково)",
    rows: 4,
    required: false,
  },
];
