export const PATIENT_FORM_FIELDS = [
  {
    name: "fullName",
    label: "ПІБ",
    component: "input",
    type: "text",
    placeholder: "Введіть повне імʼя пацієнта",
    required: true,
  },
  {
    name: "birthDate",
    label: "Дата народження",
    component: "input",
    type: "date",
    placeholder: "",
    required: true,
  },
  {
    name: "gender",
    label: "Стать",
    component: "select",
    required: true,
    options: [
      { value: "male", label: "Чоловіча" },
      { value: "female", label: "Жіноча" },
    ],
  },
  {
    name: "phone",
    label: "Телефон",
    component: "input",
    type: "tel",
    placeholder: "+380 XX XXX XX XX",
    required: true,
  },
  {
    name: "email",
    label: "Email",
    component: "input",
    type: "email",
    placeholder: "example@email.com",
    required: true,
  },
  {
    name: "address",
    label: "Адреса",
    component: "input",
    type: "text",
    placeholder: "Місто, вулиця, будинок",
    required: true,
  },
  {
    name: "notes",
    label: "Додаткові нотатки",
    component: "textarea",
    placeholder: "Додаткова інформація про пацієнта (необовʼязково)",
    rows: 4,
    required: false,
  },
];
